version: "3.7"
networks:
  be_uterace: {}

services:
  user-service:
    container_name: user-service
    image: doanquocbao4117/be-uterace:1.0
    ports:
      - "8000:8000"
    networks:
      - be_uterace